/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Conexion.Conexion;
import Datos.Dlibros;
import Logica.Libros;
import Logica.Linventario;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class FrmAltaBajaLibros extends javax.swing.JInternalFrame {

    
    public static Conexion cc = new Conexion();
    Connection cn = cc.conectar();
    Dlibros dl=new Dlibros();
    String operacion;
    int libroId;
    //con es el contador que nos ayudara a saber cuandos ejemplares estan siendo dados de alta:
        int  con=0;
    /**
     * Creates new form FrmAltaBajaLibros
     */
    public FrmAltaBajaLibros() {
        initComponents();
        mostrarLibros();
        deshabilitar();
        lblId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnDarBaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        comboBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtEjemplares = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        lblTotalLibros = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnReportar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alta/Baja Libros");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ABlibro.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 650));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lblLibros.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Autor:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Titulo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ISBN:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Editorial:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Edición:");

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtAutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        txtIsbn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtEditorial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorialActionPerformed(evt);
            }
        });

        txtEdicion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicionActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnDarBaja.setText("Dar de Baja");
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Titulo", "Autor", "ISBN", "Editorial", "Edición", "Area", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibrosMouseClicked(evt);
            }
        });
        tblLibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblLibrosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLibros);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N

        comboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por Folio:", "Buscar por ISBN:", "Buscar por Titulo:", "Buscar por Autor:", "Buscar por Editorial:", "Buscar por Edicion:", "Buscar por Estado:", "Buscar por Area:" }));
        comboBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBuscarActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ejemplares:");

        txtEjemplares.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEjemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEjemplaresActionPerformed(evt);
            }
        });
        txtEjemplares.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEjemplaresKeyReleased(evt);
            }
        });

        jLabel9.setPreferredSize(new java.awt.Dimension(300, 20));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblTotalLibros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalLibros.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblArea.setText("Area:");

        txtArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnReportar.setText("Reportar");
        btnReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setPreferredSize(new java.awt.Dimension(214, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEditorial, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIsbn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAutor)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtArea)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(123, 123, 123))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnReportar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblId)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDarBaja)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscar)
                                .addComponent(btnActualizar)
                                .addComponent(btnLimpiar)
                                .addComponent(btnReportar))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotalLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                    .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void mostrarLibros(){
    DefaultTableModel modelo=dl.mostrarLibros();
    tblLibros.setModel(modelo);
    lblTotalLibros.setText("Se encontraron: "+dl.getTotalLibros()+" Resultados");
    }
    
    public void limpiar(){
        lblId.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        txtIsbn.setText("");
        txtEditorial.setText("");
        txtEdicion.setText("");
        txtEjemplares.setText("");
        lblTotalLibros.setText("");
        txtBuscar.setText("");
        txtArea.setText("");
        
    }
    
    public void deshabilitar(){
    
    txtTitulo.setEnabled(false);
    txtAutor.setEnabled(false);
    txtIsbn.setEnabled(false);
    txtEditorial.setEnabled(false);
    txtEdicion.setEnabled(false);
    txtEjemplares.setEnabled(false);
    btnGuardar.setEnabled(false);
    btnCancelar.setEnabled(false);
    btnEditar.setEnabled(true);
    btnNuevo.setEnabled(true);
    txtArea.setEnabled(false);
    btnDarBaja.setEnabled(true);
    }
    
    public void habilitar(){
    
    txtTitulo.setEnabled(true);
    txtAutor.setEnabled(true);
    txtIsbn.setEnabled(true);
    txtEditorial.setEnabled(true);
    txtEdicion.setEnabled(true);
    txtArea.setEnabled(true);
    txtEjemplares.setEnabled(true);
    btnGuardar.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnEditar.setEnabled(false);
    btnDarBaja.setEnabled(false);
    }
    
    public String extraerCombo(){
    String consulta=null,combo;
    
    combo=comboBuscar.getSelectedItem().toString();
    
    if(combo.equals("Buscar por Folio:")){
    consulta="id_unico";
    }if(combo.equals("Buscar por Titulo:")){
    consulta="titulo";
    }    
    if(combo.equals("Buscar por ISBN:")){
     consulta="isbn";   
    }
    if(combo.equals("Buscar por Autor:")){
     consulta="autor";      
    }
    if(combo.equals("Buscar por Editorial:")){
    consulta="editorial";
    }
    if(combo.equals("Buscar por Edicion:")){
    consulta="edicion";
    }
    if(combo.equals("Buscar por Estado:")){
    consulta="estadoLibro";
    }
    if(combo.equals("Buscar por Area:")){
    consulta="nombre_area";
    }
    return consulta;
    }
    
    public void buscar(){
    Dlibros dl1=new Dlibros();
    String consulta=extraerCombo();
    DefaultTableModel modelo=dl1.consultar(consulta,txtBuscar.getText());
    tblLibros.setModel(modelo);
    lblTotalLibros.setText("Se encontraron: "+dl1.getTotalLibros()+" Resultados");
    }
    //Este metodo nos permitira validar la existencia del area ingresada 
    public int validarArea(String area){
    int idArea=0;
    try{
    String sql="SELECT area_id FROM Areas WHERE nombre_area='"+area+"' AND estado!='BAJA'";
            PreparedStatement pst= (PreparedStatement) cn.prepareStatement(sql);
            ResultSet rst = pst.executeQuery();
           if(rst.next()){
               idArea=rst.getInt("area_id");
           
           }else{
            JOptionPane.showMessageDialog(null,"El Area que ingreso es incorrecta o no existe, verifique por favor!","Error",JOptionPane.ERROR_MESSAGE);
           }            
    }catch(SQLException ex){
      JOptionPane.showMessageDialog(null,"El Area que ingreso es incorrecta o no existe, verifique por favor!","Error",JOptionPane.ERROR_MESSAGE);
    }
    return idArea;
    }
    //Este metodo nos permitira pasar los atributos a la clase Libros para que a su vez este se los proporcione
    //al metodo editarLibro de la clase Dlibros:
    public void editarLibro(int area_id){
    
    Dlibros dl2=new Dlibros();    
    Libros l=new Libros();
    l.setLibroId(libroId); 
    l.setTitulo(txtTitulo.getText());
    l.setAutor(txtAutor.getText());
    l.setIsbn(txtIsbn.getText());
    l.setEditorial(txtEditorial.getText());
    l.setEdicion(txtEdicion.getText());
    l.setAreaId(area_id);
    dl2.editarLibro(l);
    mostrarLibros();  
    libroId=0;
    }
    
    public void nuevoLibro(){
    int areaId=validarArea(txtArea.getText());
     
    Libros l=new Libros();
    l.setLibroId(libroId); 
    l.setTitulo(txtTitulo.getText());
    l.setAutor(txtAutor.getText());
    l.setIsbn(txtIsbn.getText());
    l.setEditorial(txtEditorial.getText());
    l.setEdicion(txtEdicion.getText());
    l.setAreaId(areaId);
    dl.agregarLibroNuevo(l);
    }
    //Este metodo nos ayudara a insertar los ejemplares en el inventario_Libros :
    public void nuevoEjemplar(int nEjemplares,int idLibro){
        
    Linventario i=new Linventario();
    i.setEstado("ALTA");
    i.setIdLibro(idLibro);
    //Este ciclo insertara los ejemplares de acuerdo al numero que queramos
    for(int x=0;x<nEjemplares;x++){
    String id=generarEjemplarId(); 
    if(validarIdEjemplar(id)){
    JOptionPane.showMessageDialog(null,"El folio de este ejemplar, ya se encuentra registrado, intente de nuevo por favor","ERROR",JOptionPane.ERROR_MESSAGE);
    }else{
    i.setIdUnico(id);
    dl.agregarEjemplar(i);
    }     
    }
    if(dl.isValidarRegistroEjemplar()){
        con++;
    }
    }
    //Este metodo sirve para verificar la existencia del id de algun ejemplar:
    public boolean validarIdEjemplar(String idEjemplar){
        
        boolean si=false;
        try{
        String sql="SELECT id_unico FROM inventario_Libros WHERE id_unico='"+idEjemplar+"' AND estadoLibro!='BAJA'";
            PreparedStatement pst= (PreparedStatement) cn.prepareStatement(sql);
            ResultSet rst = pst.executeQuery();
           if(rst.next()){
               
               
              si=true;
           }else{
           
           si=false;
           }    
    }catch(SQLException ex){
      JOptionPane.showMessageDialog(null,"Error al verificar la existencia de este Ejemplar"+ex,"Error",JOptionPane.ERROR_MESSAGE);
    }
    return si;    
    }
    public String generarEjemplarId(){
    String id=null;
     Calendar fecha=Calendar.getInstance();
    int a=fecha.get(Calendar.YEAR)-2000,m=fecha.get(Calendar.MONTH)+1,d=fecha.get(Calendar.DATE),h=fecha.get(Calendar.HOUR),
    mn=fecha.get(Calendar.MINUTE),s=fecha.get(Calendar.SECOND),n=fecha.get(Calendar.MILLISECOND);
    String ano=Integer.toString(a),mes=Integer.toString(m),dia=Integer.toString(d),hora=Integer.toString(h),
    minuto=Integer.toString(mn),segundo=Integer.toString(s),milisegundo=Integer.toString(n);
    if(m<10){
     mes="0"+mes;
    }
    if(d<10){
     dia="0"+dia;   
    }
    if(h<10){
     hora="0"+hora;   
    }
    if(mn<10){
     minuto="0"+minuto;   
    }
    if(s<10){
     segundo="0"+segundo;   
    }
    if(n<10){
     milisegundo="0"+milisegundo;
    }
    id=ano+mes+dia+hora+minuto+segundo+milisegundo;    
    
    return id;
    }
    
    private void txtEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEdicionActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed
    public void extraerCarrera(){
    
    }
    private void txtEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialActionPerformed

    private void comboBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBuscarActionPerformed

    private void txtEjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEjemplaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEjemplaresActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Este boton implementara el metodo buscar el cual nos mostrara el resultado de la busqueda en la tabla
        if(!txtBuscar.getText().equals("")){
            buscar();
        }else{
             mostrarLibros();
            }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // Este metodo implementa la funcio del boton Actualizar:
        
        limpiar();
        mostrarLibros();
        deshabilitar();
       
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed
        Linventario i=new Linventario();
        
        if(!lblId.getText().equals("")){
        int r=JOptionPane.showConfirmDialog(null,"Desea dar de baja a este Ejemplar?","Confirmación",JOptionPane.YES_NO_OPTION);
        
        
        if(r==JOptionPane.YES_OPTION){
        dl.bajaEjemplar(lblId.getText());
        }
        }
        limpiar();
        deshabilitar();
        mostrarLibros();
    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
    if(comboBuscar.getSelectedItem().toString().equals("Buscar por Estado:")){
    char keyChar = evt.getKeyChar();
    if (Character.isLowerCase(keyChar)) {
      evt.setKeyChar(Character.toUpperCase(keyChar));
    }
    }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        habilitar();
        operacion="nuevo";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // este metodo implementara la funcion del boton cancelar que devolvera con el metodo deshabilitar al estado inicial
        limpiar();
        deshabilitar();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!txtBuscar.getText().equals("")){
            buscar();
        }else{
             mostrarLibros();
            }
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void tblLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibrosMouseClicked
        // Este metodo visualiza los datos de la tabla en los campos de texto al hacer click:
      
        int fila = tblLibros.rowAtPoint(evt.getPoint());
        lblId.setText(tblLibros.getValueAt(fila,0).toString());
        txtTitulo.setText(tblLibros.getValueAt(fila,1).toString());
        txtAutor.setText(tblLibros.getValueAt(fila,2).toString());
        txtIsbn.setText(tblLibros.getValueAt(fila,3).toString());
        txtEditorial.setText(tblLibros.getValueAt(fila,4).toString());
        txtEdicion.setText(tblLibros.getValueAt(fila,5).toString());
        txtArea.setText(tblLibros.getValueAt(fila,6).toString());
        
    }//GEN-LAST:event_tblLibrosMouseClicked

    private void tblLibrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLibrosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLibrosKeyPressed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        if(!txtTitulo.getText().equals("")){
        operacion="editar";
        libroId=generarLibroId();
        habilitar();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //este metodo ejecutara el metodo agregar nuevo libro o editarLibro segun sea el caso:
        int area_id=validarArea(txtArea.getText());
        
        if(area_id!=0){
        if(operacion.equals("nuevo")){
            if(lblId.getText().equals("")){
            nuevoLibro();
            if(dl.isValidarRegistoLibro()){
            libroId=generarLibroId();
            int nEjemplares=Integer.parseInt(txtEjemplares.getText());
            nuevoEjemplar(nEjemplares, libroId);
            }
            ImageIcon icon=new ImageIcon(getClass().getResource("/imagenes/bien.png"));
            JOptionPane.showMessageDialog(null,"Se han registrado: "+con+" Ejemplares","Operación Exitosa",JOptionPane.INFORMATION_MESSAGE,icon);
            }else{
            libroId=generarLibroId();
            int nEjemplares=Integer.parseInt(txtEjemplares.getText());
            nuevoEjemplar(nEjemplares, libroId);
            ImageIcon icon=new ImageIcon(getClass().getResource("/imagenes/bien.png"));
            JOptionPane.showMessageDialog(null,"Se han registrado: "+con+" Ejemplares","Operación Exitosa",JOptionPane.INFORMATION_MESSAGE,icon);
        }
        
        }if(operacion.equals("editar")){
          editarLibro(area_id);
          limpiar();
          deshabilitar();
        }
        }
        mostrarLibros();
        con=0;
        limpiar();
        operacion="";
        deshabilitar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarActionPerformed
     // TODO add your handling code here:
    if(!lblId.getText().equals("")){
    String nuevoEstado=JOptionPane.showInputDialog(this,"Como desea reportar este ejemplar?","Reporte de Libros");
    dl.reporteEjemplar(nuevoEstado.toUpperCase(),lblId.getText() );
    }
    limpiar();
    deshabilitar();
     mostrarLibros();
    }//GEN-LAST:event_btnReportarActionPerformed
   
    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        if(!txtBuscar.getText().equals("")){
        buscar();
        }else{
        mostrarLibros();
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtEjemplaresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEjemplaresKeyReleased
        //En este metodo validamos que no se ingresen letras u otros simbolos en el campo ejemplares:
        int k=evt.getKeyChar();
        if(k>0 && k<7 || k>10 && k<48 || k>57 && k<255){

            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null,"Solo se pueden ingresar numeros en este campo","Error",JOptionPane.ERROR_MESSAGE);
            txtEjemplares.setText("");
        }
    }//GEN-LAST:event_txtEjemplaresKeyReleased
    
    
    
    //Este metodo nos permitira realizar una consulta que nos generara el id del libro a la hora de dar de alta ejemplares:
    public int generarLibroId(){
    int dato=0;
    try{
    String sql="SELECT libro_id FROM Libro WHERE titulo="+'"'+txtTitulo.getText()+'"'+" AND autor="+'"'+txtAutor.getText()+'"'+"AND isbn="+'"'+txtIsbn.getText()+'"'+" AND editorial="+'"'+txtEditorial.getText()+'"'+" AND edicion="+'"'+txtEdicion.getText()+'"';
            PreparedStatement pst= (PreparedStatement) cn.prepareStatement(sql);
            ResultSet rst = pst.executeQuery();
            if(rst.next()){
            dato=rst.getInt("libro_id");
            }
    }catch(SQLException ex){
      JOptionPane.showMessageDialog(null,"Error al realizar la consulta"+ex,"ERROR", JOptionPane.ERROR_MESSAGE);
    
    }
    return dato;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDarBaja;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReportar;
    private javax.swing.JComboBox<String> comboBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTotalLibros;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtEjemplares;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
